version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    networks:
      - my_network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://vickie:newpassword@localhost/db/microblog
      - "TEST_DATABASE_URL=sqlite+aiosqlite:///:memory:"
    ports:
      - "5000:5000"
    restart: always
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=microblog
      - POSTGRES_USER=vickie
      - POSTGRES_PASSWORD=newpassword
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
