"""Add files to Media

Revision ID: 07a9dfc5a5c5
Revises: 015089f4d2e2
Create Date: 2025-01-12 19:09:29.294696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a9dfc5a5c5'
down_revision: Union[str, None] = '015089f4d2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_body', sa.LargeBinary(), nullable=True))
    op.add_column('media', sa.Column('file_name', sa.String(), nullable=True))
    op.drop_column('media', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('media', 'file_name')
    op.drop_column('media', 'file_body')
    # ### end Alembic commands ###
