"""Allow NULL in tweet_id for Media

Revision ID: ae76cbd93c97
Revises: 07a9dfc5a5c5
Create Date: 2025-01-14 14:51:15.739043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae76cbd93c97'
down_revision: Union[str, None] = '07a9dfc5a5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
