name: CI Test Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Шаг 3: Собираем контейнер и запускаем сервис
      - name: Build and start services
        run: docker-compose -f docker-compose.yml up -d --build

      # Шаг 4: Запускаем тесты внутри контейнера
      - name: Run tests inside container
        run: docker-compose exec pytest -v -c tests/pytest.ini

      # Шаг 5: Останавливаем и удаляем контейнеры после тестов
      - name: Clean up
        run: docker-compose down
