name: CI Test Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: my-test-image:latest  # Используем кастомный образ
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-test-image -f server/Dockerfile .

      - name: Run tests
        run: |
          cd server/tests
          python -m pytest -c pytest.ini
