name: CI Test Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image  # Собираем Docker-образ
        run: docker build -t my-test-image -f server/Dockerfile .

      - name: Run tests inside container  # Запускаем тесты внутри контейнера
        run: docker run --rm my-test-image pytest -c server/tests/pytest.ini
