name: CI Test Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start services
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Show container logs
        run: docker-compose logs app

      - name: Install dependencies
        run: docker-compose exec -T app pip install -r requirements.txt

      - name: Run tests with detailed output
        run: docker-compose exec -T app pytest -v -c server/tests/pytest.ini

      - name: Clean up
        run: docker-compose down

